// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMN2Mhyx4Croh6KqlSmogi5b8l6q7h4o',
    appId: '1:428475070202:web:7f0d91cc9f417823a9bb43',
    messagingSenderId: '428475070202',
    projectId: 'hand-sign-app-c4e06',
    authDomain: 'hand-sign-app-c4e06.firebaseapp.com',
    storageBucket: 'hand-sign-app-c4e06.firebasestorage.app',
    measurementId: 'G-XMTEFBQ6DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD44F9U8vCuQMAEIlF9Y_9KuoVW9VcyUM',
    appId: '1:428475070202:android:1234ab837e5904e7a9bb43',
    messagingSenderId: '428475070202',
    projectId: 'hand-sign-app-c4e06',
    storageBucket: 'hand-sign-app-c4e06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoRYJbJDWUiG9tikvwxAobUQtCFyiyJfg',
    appId: '1:428475070202:ios:81b28d295ba57e33a9bb43',
    messagingSenderId: '428475070202',
    projectId: 'hand-sign-app-c4e06',
    storageBucket: 'hand-sign-app-c4e06.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoRYJbJDWUiG9tikvwxAobUQtCFyiyJfg',
    appId: '1:428475070202:ios:81b28d295ba57e33a9bb43',
    messagingSenderId: '428475070202',
    projectId: 'hand-sign-app-c4e06',
    storageBucket: 'hand-sign-app-c4e06.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDMN2Mhyx4Croh6KqlSmogi5b8l6q7h4o',
    appId: '1:428475070202:web:ac08bfbba8ca43f7a9bb43',
    messagingSenderId: '428475070202',
    projectId: 'hand-sign-app-c4e06',
    authDomain: 'hand-sign-app-c4e06.firebaseapp.com',
    storageBucket: 'hand-sign-app-c4e06.firebasestorage.app',
    measurementId: 'G-Q63YCWFSZE',
  );
}
